[pytest]
python_files = test_*.py
required_plugins = pytest-odoo
testpaths = custom_modules/customer_credit_control/tests
addopts = --cov=customer_credit_control
          --cov-report=term-missing
          --cov-config=.coveragerc
          --odoo-database=postgres
          --odoo-log-level=error